#ManagedBy: cue

patchesStrategicMerge:
  - patch-namespace-knative-serving.yaml
  - patch-deployment-webhook.yaml
  - patch-deployment-domainmappingwebhook.yaml
  - patch-deployment-autoscaler.yaml
  - patch-deployment-activator.yaml
  - patch-config-map-config-defaults.yaml
  - patch-config-map-config-domain.yaml
  - patch-config-map-config-features.yaml
  - patch-config-map-config-network.yaml
resources:
  - https://github.com/knative/serving/releases/download/knative-v1.7.2/serving-core.yaml
