annotations:
  artifacthub.io/changes: |
    - "[Fixed]: tpl function related errors"
apiVersion: v2
appVersion: v0.4.0
description: A Kubernetes webhook for pods that need AWS IAM access
home: https://github.com/aws/amazon-eks-pod-identity-webhook/
keywords:
- aws
- iam
- eks
- irsa
- iam-roles-for-service-accounts
- eks-pod-identity-webhook
- aws-pod-identity-webhook
maintainers:
- email: github@jkroepke.de
  name: jkroepke
  url: https://github.com/jkroepke
name: amazon-eks-pod-identity-webhook
sources:
- https://github.com/jkroepke/helm-charts/tree/main/charts/amazon-eks-pod-identity-webhook
- https://github.com/aws/amazon-eks-pod-identity-webhook/
type: application
version: 1.0.3
