#ManagedBy: cue

patchesStrategicMerge:
  - patch-deployment-karpenter-irsa.yaml
resources:
  - karpenter.yaml
  - resource-namespace-karpenter.yaml
  - resource-provisioner-control-vc0.yaml
  - resource-provisioner-control-vc1.yaml
  - resource-provisioner-control-vc2.yaml
  - resource-provisioner-control-vc3.yaml
  - resource-provisioner-control-vc4.yaml
namespace: karpenter
