#ManagedBy: cue

patchesStrategicMerge: []
resources: []
helmCharts:
  - releaseName: bootstrap
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    valuesInline:
      anyResources:
        cert-manager: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-smiley-cert-manager
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: k3d-smiley
            source:
              repoURL: https://github.com/amanibhavam/dotfiles
              targetRevision: master
              path: k/cert-manager
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        pod-identity-webhook: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-smiley-pod-identity-webhook
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-smiley
            source:
              repoURL: https://github.com/amanibhavam/dotfiles
              targetRevision: master
              path: k/pod-identity-webhook
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        kyverno: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-smiley-kyverno
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-smiley
            source:
              repoURL: https://github.com/amanibhavam/dotfiles
              targetRevision: master
              path: k/kyverno
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        external-secrets-operator: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-smiley-external-secrets-operator
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-smiley
            source:
              repoURL: https://github.com/amanibhavam/dotfiles
              targetRevision: master
              path: k/external-secrets-operator
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        k3d-smiley-secrets-store: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-smiley-secrets-store
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-smiley
            source:
              repoURL: https://github.com/amanibhavam/dotfiles
              targetRevision: master
              path: k/k3d-smiley-secrets-store
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        k3d-smiley-kuma-zone: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-smiley-kuma-zone
            annotations:
              argocd.argoproj.io/sync-wave: "30"
          spec:
            project: default
            destination:
              name: k3d-smiley
            source:
              repoURL: https://github.com/amanibhavam/dotfiles
              targetRevision: master
              path: k/k3d-smiley-kuma-zone
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        tfo: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-smiley-tfo
            annotations:
              argocd.argoproj.io/sync-wave: "30"
          spec:
            project: default
            destination:
              name: k3d-smiley
            source:
              repoURL: https://github.com/amanibhavam/dotfiles
              targetRevision: master
              path: k/tfo
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        demo1: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-smiley-demo1
            annotations:
              argocd.argoproj.io/sync-wave: "40"
          spec:
            project: default
            destination:
              name: k3d-smiley
            source:
              repoURL: https://github.com/amanibhavam/dotfiles
              targetRevision: master
              path: k/demo1
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
        demo2: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-smiley-demo2
            annotations:
              argocd.argoproj.io/sync-wave: "40"
          spec:
            project: default
            destination:
              name: k3d-smiley
            source:
              repoURL: https://github.com/amanibhavam/dotfiles
              targetRevision: master
              path: k/demo2
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
    includeCRDs: true
