#ManagedBy: cue

patchesStrategicMerge:
  - patch-statefulset-vault-set-vault-token.yaml
resources: []
namespace: vault
helmCharts:
  - releaseName: vault
    name: vault
    version: 0.20.1
    repo: https://helm.releases.hashicorp.com
    namespace: vault
    valuesInline:
      server:
        dataStorage:
          size: 1Gi
        standalone:
          config: |
            disable_mlock = true
            ui = true

            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }

            storage "file" {
              path = "/vault/data"
            }

            seal "transit" {
              address = "http://vault.default.svc:8200"
              disable_renewal = "false"
              key_name = "autounseal-remo"
              mount_path = "transit/"
              tls_skip_verify = "true"
            }
    includeCRDs: true
