#ManagedBy: cue

patchesStrategicMerge: []
resources: []
helmCharts:
  - releaseName: bootstrap
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    valuesInline:
      anyResources:
        cert-manager: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: vcluster-vc2-cert-manager
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: vcluster-vc2
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/cert-manager
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
            ignoreDifferences:
              - group: ""
                kind: Secret
                jsonPointers:
                  - /data
                name: karpenter-cert
                namespace: karpenter
    includeCRDs: true
