#ManagedBy: cue

patchesStrategicMerge: []
resources:
  - resource-namespace-kuma.yaml
namespace: kuma
helmCharts:
  - releaseName: kuma
    name: kuma
    version: 1.8.1
    repo: https://kumahq.github.io/charts
    namespace: kuma
    valuesInline:
      controlPlane:
        mode: global
        service:
          type: LoadBalancer
        tls:
          general:
            secretName: generic-tls-cert
            caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiekNDQWxlZ0F3SUJBZ0lSQUt1M3pPcFVGUVVtRjJtZFhrdkRNZmN3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXhNWGEzVnRZUzFqYjI1MGNtOXNMWEJzWVc1bExtdDFiV0V3SGhjTk1qSXhNREV3TURVMApOakl5V2hjTk16SXhNREEzTURVME5qSXlXakFpTVNBd0hnWURWUVFERXhkcmRXMWhMV052Ym5SeWIyd3RjR3hoCmJtVXVhM1Z0WVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnhHK0FsZXM2QVMKc2Y4ZXM4VWx4Q1lrV1kxeURpUUpwT3VQd1BOWERiamJmcXZCQVg1YkNIeGo0by9RVkdRTm04RlBleW9KT0p1NgppWmFYa2xCbG1RVGJuTTl2TVZlZE5lbjlteUZhM0YwV0xMUlFjYmF0bTRSNUY5c0lZQzRiY2J3bXMxSTROQUlMCnhxU1puR096THZzMDRGaThXK2FtZS9pRkt6emdlZW5uV2VsTTF4aSthM0dzU0NkRlEvaEt1UmNZMW5OZTFhNmQKY1hWaHRDSWF1S2dWWWRybVlDeUNoczBXbFlrZWxVQ1czcVJrV1dkMDhTbVd2TFB3dDdVUXlNb1JVc2kxTkdYZQpFdk5Sd1BWS29ZS0UzZ1p3eDA3TjcvaUdvVjFSc3dqclNRTjFyTnV5WTFmTFVYNXhCS2cwTlAwMnMrN3hteCtaCnd6d0d5K1hEZDhFQ0F3RUFBYU9CbnpDQm5EQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVYlBhV1lCNm5NSkl6bStregpuWDdPTG9zUXlXOHdSUVlEVlIwUkJENHdQSUlYYTNWdFlTMWpiMjUwY205c0xYQnNZVzVsTG10MWJXR0NHMnQxCmJXRXRZMjl1ZEhKdmJDMXdiR0Z1WlM1cmRXMWhMbk4yWTRjRVpFQnVFREFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQVFxK2pzSXRHV09qcWZFRWI5TzZndnNJakNPWWVIVWsyUi9mUkZhZGFlVFRUZU5xODc2cU10T0kvSmZOcgpLUmZvN25idkdNTGMyZVJQUmNsZUlLcjZUY1VIU3dXdG5YNGVWR2o4VGtORVV0NXhyeUlRMTc4NFRoemU3eUtKCm12dWtoL0hyTG5aR2dDWWJsOEFUSUcwek94cXlyRDQvR05CK0p4QVZDemtiYldYU3VtZk81bnBLUWdtUllkS08KV29iZ0QzMDBOdVB1QmRJS3Jrc1A5N3lWdE90ck1weGg0MENPdi9jMUZHRHB3RXN2MFJhS2doQVF5emlSc2xlUgpJY0JkOGgwRXpzaU1nZVZTdXdURHZTNG1YWWxBcVdhcjNEek9NQkdXaG9RUFY2bWM1Szh5QnVlM3FZRE5jdklwCjdGekEySjVQdkV2SVlwVWZWRUlUT2J1SmR3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
          kdsGlobalServer:
            secretName: kds-server-tls
    includeCRDs: true
